# PARAMETER NAMES
NUM_EPOCHS = "NUM_EPOCHS"
NUM_EPISODES = 'NUM_EPISODES'
MAX_STEPS_PER_EPISODE = 'MAX_STEPS_PER_EPISODE'
BATCH_SIZE = 'BATCH_SIZE'
GAMMA = 'GAMMA'

LEARNING_RATE = 'LEARNING_RATE'
CLIPPING_LOSS_RATIO = 'CLIPPING_LOSS_RATIO'

MAX_GRADIENT_NORM = 'MAX_GRADIENT_NORM'

UPDATE_STEP_INTERVAL = 'UPDATE_STEP_INTERVAL'
BUFFER_CAPACITY = 'BUFFER_CAPACITY'

EPSILON = 'EPSILON'
RHO = 'RHO'
DISCOUNT_FACTOR = "DISCOUNT_FACTOR"

REWARD_GOAL = 'REWARD_GOAL'
CONSECUTIVE_GOAL_HITS = 'CONSECUTIVE_GOAL_HITS'
REWARD_CALCULATED_FROM_SINGLE_EPISODES = 'REWARD_CALCULATED_FROM_SINGLE_EPISODES'


ENV_NAME = 'ENV_NAME'
# ENV_DISPLAY_ON = 'ENV_DISPLAY_ON'

DEQUE_MEM_SIZE = 'DEQUE_MEM_SIZE'
EPSILON_MIN = 'EPSILON_MIN'
EPSILON_DECAY = 'EPSILON_DECAY'

LEARNING_LIBRARY = 'LEARNING_LIBRARY'
MODEL_FOLDER_DOT_PATH = 'MODEL_FOLDER_DOT_PATH'

ACTION_DIMENSIONS = 'ACTION_DIMENSIONS'
STATE_DIMENSIONS = 'STATE_DIMENSIONS'

ENV_REPO = 'ENV_REPO'

ACTOR_HIDDEN_LAYER_NODES = "ACTOR_HIDDEN_LAYER_NODES"
CRITIC_HIDDEN_LAYER_NODES = "CRITIC_HIDDEN_LAYER_NODES"

NUM_NODES = "NUM_NODES"
ACTIVATION_FN = "ACTIVATION_FN"

RESULTS_BASE_PATH = 'RESULTS_BASE_PATH'
RESULTS_CURRENT_PATH = 'RESULTS_CURRENT_PATH'
RESULTS_ARCHIVE_PATH = 'RESULTS_ARCHIVE_PATH'
MODEL_FILE_NAME = 'MODEL_FILE_NAME'

ARCHIVES = 'Archives'


MAX_RESULT_COUNT = "MAX_RESULT_COUNT"

SD_FOR_MULTIVARIATE_NORMAL_ACTION_DISTRIBUTION = "SD_FOR_MULTIVARIATE_NORMAL_ACTION_DISTRIBUTION"

APP_INFO_SOURCE = 'APP_INFO_SOURCE'

APP_INFO_FILE = 'demo_APP_INFO.JSON'
NUM_EPISODES_FOR_UPDATE = 'NUM_EPISODES_FOR_UPDATE'
ENV_SEED = 'ENV_SEED'

# DIRECTORY NAMES
AGENTS_DIR = 'RLAgents'
ENVS_DIR = 'RLEnvs'
DEMO_PATH = 'DEMO_PATH'

STRATEGY = 'STRATEGY'

AGENT_FOLDER_PATH = 'AGENT_FOLDER_PATH'
ARCHIVE_SUB_FOLDER = 'ARCHIVE_SUB_FOLDER'

OBJ_EPISODE = 'OBJ_EPISODE'

GPU_DEVICE = 'GPU_DEVICE'
FORCE_CPU_USE = 'FORCE_CPU_USE'

BOARD_SIZE = 'BOARD_SIZE'

LAYER_TYPE = 'LAYER_TYPE'
IN_CHANNELS = 'IN_CHANNELS'
OUT_CHANNELS = 'OUT_CHANNELS'
KERNEL_SIZE = 'KERNEL_SIZE'
STRIDE = 'STRIDE'
PADDING = 'PADDING'
NUM_FEATURES = 'NUM_FEATURES'

LOG_SKIP_INTERVAL = 'LOG_SKIP_INTERVAL'
LOG_MEAN_INTERVAL = 'LOG_MEAN_INTERVAL'

FN_RECORD = 'fn_log'
DEBUG_MODE = 'DEBUG_MODE'




